name: run-migrations-on-main
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: DAGLIG_MONGODB_URL=${{ secrets.DAGLIG_MONGODB_URL }} node migrations/migrate.mjs
